#!/usr/bin/env node
// Regenerates `src/lib/contracts/abis.ts` from `forge build` output (`contracts/out/`).
// Never hand-copy an ABI — run `npm run contracts:abis` (or `npm run contracts:build`, which
// calls this automatically) after any contract change instead.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const contractsDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(contractsDir, "out");
const targetFile = path.resolve(contractsDir, "../src/lib/contracts/abis.ts");
const bytecodeTargetFile = path.resolve(contractsDir, "../src/lib/contracts/bytecode.ts");

// Own AgentVillage contracts, plus the real ENSv2 interfaces the read layer calls directly
// against ENSv2's own deployed contracts (`ETHRegistry`, `UniversalResolver`).
const artifacts = {
  agentRegistryAbi: "AgentRegistry.sol/AgentRegistry.json",
  agentResolverAbi: "AgentResolver.sol/AgentResolver.json",
  wildcardResolverAbi: "WildcardResolver.sol/WildcardResolver.json",
  wildcardStateStoreAbi: "WildcardStateStore.sol/WildcardStateStore.json",
  ethRegistryAbi: "IPermissionedRegistry.sol/IPermissionedRegistry.json",
  // `resolve(bytes,bytes)` itself lives on the ENSv1-style base `IUniversalResolver`, not the
  // ENSv2-specific helper interface `IUniversalResolverV2` (which only adds
  // findOwner/findRegistries/etc) — `UniversalResolverV2` implements both.
  universalResolverAbi: "IUniversalResolver.sol/IUniversalResolver.json",
  enhancedAccessControlAbi: "IEnhancedAccessControl.sol/IEnhancedAccessControl.json",
  // Registration flow against the hackathon `ETHRegistrar` (task 30/31) — includes
  // MIN_COMMITMENT_AGE/MAX_COMMITMENT_AGE getters so the UI reads them instead of hardcoding.
  ethRegistrarAbi: "IETHRegistrarWithConstants.sol/IETHRegistrarWithConstants.json",
  // Minimal mintable-ERC20 surface for the hackathon `MockUSDC` payment token.
  erc20Abi: "IMockERC20.sol/IMockERC20.json",
};

let out = [
  "// AUTO-GENERATED by `contracts/script/export-abis.mjs` from `forge build` output.",
  "// Do not hand-edit — run `npm run contracts:abis` (or `npm run contracts:build`) instead.",
  "/* eslint-disable */",
  "",
].join("\n");

for (const [exportName, relPath] of Object.entries(artifacts)) {
  const artifact = JSON.parse(readFileSync(path.join(outDir, relPath), "utf8"));
  out += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}

writeFileSync(targetFile, out);
console.log(`Wrote ${targetFile}`);

// Task 32: contracts the UI deploys itself (one per kingdom a user founds), so their creation
// bytecode has to ship to the browser too — kept in a separate, dynamically-imported file so it
// never bloats the main bundle for the (common) case of a visitor who never founds a kingdom.
const deployableArtifacts = {
  agentRegistryBytecode: "AgentRegistry.sol/AgentRegistry.json",
  wildcardStateStoreBytecode: "WildcardStateStore.sol/WildcardStateStore.json",
  wildcardResolverBytecode: "WildcardResolver.sol/WildcardResolver.json",
};

let bytecodeOut = [
  "// AUTO-GENERATED by `contracts/script/export-abis.mjs` from `forge build` output.",
  "// Do not hand-edit — run `npm run contracts:abis` (or `npm run contracts:build`) instead.",
  "//",
  "// Task 32: creation bytecode for the contracts a user's own wallet deploys when founding a",
  "// kingdom (one `AgentRegistry` + `WildcardStateStore` + `WildcardResolver` per claimed name).",
  "// Import this module only from the found-kingdom flow, never at module scope of a shared file —",
  "// that's what keeps it out of the bundle everyone else pays for.",
  "",
].join("\n");

for (const [exportName, relPath] of Object.entries(deployableArtifacts)) {
  const artifact = JSON.parse(readFileSync(path.join(outDir, relPath), "utf8"));
  const bytecode = artifact.bytecode.object;
  bytecodeOut += `export const ${exportName} = "${bytecode}" as \`0x\${string}\`;\n\n`;
}

writeFileSync(bytecodeTargetFile, bytecodeOut);
console.log(`Wrote ${bytecodeTargetFile}`);
